apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 100
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 5
          initialDelaySeconds: 30
        resources:
          requests:
            cpu: "2"
            memory: 1000Mi
          limits:
            cpu: "2"
            memory: 1000Mi