apiVersion: v1
kind: Namespace
metadata:
  name: test-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
