apiVersion: v1
kind: Pod
metadata:
  name: pkad
  labels:
    name: pkad
spec:
  containers:
  - name: myapp
    image: gcr.io/kuar-demo/kuard-amd64:1
    env:
      - name: DEMO
        value: "PKAD"
      - name: ENV
        value: "Test"
