apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-file-config
data:
  appsettings.json: |-
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "AllowedHosts": "*"
    }
  config-demo.json: |-
    {
        "Bla": {}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        volumeMounts:
          - name: config
            mountPath: /app/config/
      volumes:
        - name: config
          configMap:
            name: kuard-file-config
